{
 "title": "Totals",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_bucket[60m])) by (le))"
    }
   ]
  },
  {
   "title": "Averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(score_response_sum[1h]))/sum(increase(score_response_count[1h]))",
     "legendFormat": "Score"
    },
    {
     "expr": "sum(increase(prediction_response_sum[1h]))/sum(increase(prediction_response_count[1h]))",
     "legendFormat": "Prediction"
    }
   ]
  },
  {
   "title": "Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(prediction_total[5m])" },
    {
     "expr": "rate(model_information_total[5m])"
    }
   ]
  }
 ]
}